### ISSUE TITLE
The size of tensor a (15) must match the size of tensor b (3) at non-singleton dimension 0

### ISSUE THREAD

**Issue by zeke** [0x7o/IF-replicate#1] opened 2023-05-09 15:33 UTC
Hi @0x7o 👋🏼 

Thanks for pushing this model to Replicate.

I just tried running a prediction with `num_outputs` set to 5, and I got this error:

> The size of tensor a (15) must match the size of tensor b (3) at non-singleton dimension 0

Here's the prediction if it's helpful: https://replicate.com/p/jg53gkwrsbfupl3fwxouszyw6m

**Comment by 0x7o** [comment] 2023-06-02 11:28
![image](https://github.com/0x7o/IF-replicate/assets/96177948/b7d83ac7-7bee-4503-ab14-425d84496289)
Thanks for the report! The problem is fixed in the latest update.

**Closed as completed** 2023-06-02 11:28 UTC
